### ISSUE TITLE
Missing actions in execute list

### ISSUE THREAD

**Issue by soulfire03** [bewee/macrozilla#37]
Using the macro addon, I wanted to display a toast notification on my LG TV.

With the "set attribute to value" object, the only items listed are On, Off, Mute and Active App.
And with the "execute thing action" object, I have 7x "undefined" items listed.

Would it be possible to address that please?

**Comment by bewee** [comment]
Hi @soulfire03,

I need some more information to have a look at this. First of all: Could you please tell me which adapter add-on you use to connect your LG TV to the gateway? And also: Can you use the action which you want to use in your macro in a rule? Maybe your TV's adapter changes visibility of its actions in the things view? (I can try to have a look at your TV's adapter's source if you tell me about that).
Also, it may be helpful if you could send some screenshots.

Regards :)

**Comment by soulfire03** [comment]
Hello!

I'm using the LV webOS TV adapter : 
![adapter](https://user-images.githubusercontent.com/39413022/106387827-937d0900-63a9-11eb-9aba-d55995b0db32.png)

Using the adapter in the rules page, I'm able to send a toast notification on the TV, so it's working fine : 
![rule](https://user-images.githubusercontent.com/39413022/106387850-a42d7f00-63a9-11eb-80cd-89decb9f4d21.png)

Notice that there are 3 parameters for this "toast" TV action. I don't know how this can be implemented in a macro's execute action.

Here is the macro window. Even if it's working in a rule, I wanted to do this in a macro because I would use a variable : 
![macro](https://user-images.githubusercontent.com/39413022/106388083-d2f82500-63aa-11eb-81e7-e68f63a94f12.png)

Let me know if you need something else! :)
BTW, this macro addon is a very impressive piece of work. Good job!
Thanks

**Comment by bewee** [comment]
Hi @soulfire03,

the LG TV adapter realizes the toast functionality using a notifier, not using thing's actions (I have no clue where these undefineds are from). Unfortunately, the macro add-on currently has no support for notifications. However, I opened a new issue #38 and hope we can get this implemented!

Regards :)

**Comment by bewee** [comment]
Hi @soulfire03,

I got a first version running. There are still some things to be done, but could you please already have a look at it by cloning the branch [inputActions](https://github.com/bewee/macrozilla/tree/inputActions) and give me some feedback?

Regards :)

**Comment by soulfire03** [comment]
I'm not sure on how to put the code and compile it on the Pi.

**Comment by bewee** [comment]
Hi @soulfire03,

do you have remote access (ssh) enabled on your pi (have a look at settings >> developer), and do you know hot to connect to it this way? 

Regards :)

**Comment by bewee** [comment]
Hi @soulfire03,

because I made quite a few structural changes during implementation of parameterized actions, I just released an update for the macrozilla add-on. I hope this fixes your issue (I tested everything with virtual things, and it worked well with these). If so, you can close this issue. If not, please report back :)

Regards

**Comment by soulfire03** [comment]
Yes sorry, I've been busy this weekend. 
I tried the update but I am not able to create or open an existing macro. The macro window shows but there is no objects in the left panel.
![macro](https://user-images.githubusercontent.com/39413022/107240127-8e4a3a80-69f7-11eb-9421-cc0e9e54fbb2.png)

**Comment by bewee** [comment]
Hi @soulfire03,

this should not happen! I installed the upate on my personal gateway too and experienced no such behaviour there. Could you please have a look at the developer console of your browser (tutorial: [https://balsamiq.com/support/faqs/browserconsole/](https://balsamiq.com/support/faqs/browserconsole/)) and send me the logs from there?

Regards

**Comment by soulfire03** [comment]
Oh, it was some javascript files missing. I did a hard refresh to clear the cache and it was solved.

**Comment by soulfire03** [comment]
I was able to build the macro and add the Toast action for the TV. However when I execute it or if I wait for the trigger to fire, nothing happens. I suspect that I did not build it correctly, so I will close this issue and read more carefully on how to properly create macros.
Thank you for your help

**Comment by bewee** [comment]
Alright. Feel free to re-open the issue in case you are stuck. You can also send a screenshot of your macro and I will have a look at it :)
