### ISSUE TITLE
macro and variable not showing up in the menu

### ISSUE THREAD

**Issue by arist0v** [bewee/macrozilla#64]
Hello, i have installed the macros and used it for a while, then now i don't have the entry in the menu anymore.
when i try to go to : http://gateway/extensions/macrozilla nothing appears

i tried to uninstall and reinstall but nothing help

thank you

**Comment by bewee** [comment]
Hi @arist0v,

please have a look at the add-on config. Are the options "Include macros page" and "Include variables page" checked?

Regards :)

**Comment by arist0v** [comment]
Yeah, i don't understand why it have stip showing, but now everything is
fine thank you

Le sam. 20 mars 2021 17 h 34, Benedikt Weber ***@***.***> a
écrit :

**Comment by bewee** [comment]
Glad to hear this worked :)
