### ISSUE TITLE
Modulo broken

### ISSUE THREAD

**Issue by Shadaez** [bewee/macrozilla#66]
```"stack": "instance.qualifier is not one of enum values: not,abs,negate,&,|,^,+,-,*,/,pow,%,round,cmp"```
receiving this error whenever I use mod (honestly all the math should just be a single block maybe with a dropdown tbh?

**Comment by bewee** [comment]
Hi @Shadaez !

Thanks for reporting this bug! I have released a fix, but couldn't test it on my current system. Could you please update the add-on and tell me whether everything works fine for you now?

> honestly all the math should just be a single block maybe with a dropdown tbh?

I kinda agree there. Tbh I'm not so much happy with the whole grouping feature altogether. However, switching to a dropdown would break existing macros :/ So I'm not sure whether it's really worth it...

Regards :)

**Comment by bewee** [comment]
Closing because this bug is fixed
