### ISSUE TITLE
Getting in touch

### ISSUE THREAD

**Issue by flatsiedatsie** [bewee/macrozilla#70]
Hey Benedikt, what's the best way to get in touch with you? I'd like to discus a few webthings related things if possible. I did a quick search but haven't been able to find an email address. 

If you could perhaps shoot an email to `info` at [this domain](https://www.tijmenschep.com/), that would be great.

**Comment by bewee** [comment]
Hi @flatsiedatsie 

> If you could perhaps shoot an email to info at this domain, that would be great.

Sure.

You can also find me on the webthings matrix channel.

And just fyi, you can often find a github user's mail by searching this page for the at character: https://api.github.com/users/bewee/events/public
