### ISSUE TITLE
Input actions for string types do not render properly while editing

### ISSUE THREAD

**Issue by tatemz** [bewee/macrozilla#72]
Check out the recorded GIF below and notice that users are unable to enter in a text parameter input while editing. In order to edit the string input, you have to save and reload the edit page.

![2021-07-28 20 45 11](https://user-images.githubusercontent.com/2190655/127418711-e1320f60-2afc-4e12-a0a2-ffff91763e81.gif)

Great addon btw! 💯

**Comment by bewee** [comment]
Hi @tatemz

Thank you for reporting this bug! And nice to hear that you like this addon :)

I opened a PR (#73) which should fix this issue. Could you have a look at it and report back whether this solves it for you? Thanks in advance :)

**Comment by bewee** [comment]
Merging the mentioned PR and closing this issue because this should solve it. If otherwise, raise a new issue.
